<?php
session_start();
require_once '../includes/auth.php'; require_once '../includes/messages.php'; require_role('rower'); require '../config/database.php';
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT); if(!$id){http_response_code(404);exit('Session not found.');}
$q=$pdo->prepare('SELECT * FROM sessions WHERE id=?'); $q->execute([$id]); $training=$q->fetch(); if(!$training){http_response_code(404);exit('Session not found.');}
$q=$pdo->prepare('SELECT * FROM results WHERE session_id=? AND rower_id=?'); $q->execute([$id,(int)$_SESSION['user_id']]); $result=$q->fetch()?:[];
if($training['status']!=='open'&&!$result){set_session_message('info','This session is not open for results.');header('Location: /pages/session-view.php?id='.$id);exit;}
$q=$pdo->prepare('SELECT * FROM workout_segments WHERE session_id=? ORDER BY segment_order,id'); $q->execute([$id]); $segments=$q->fetchAll();
$saved_segment_notes=[];$saved_intervals=[];
if(!empty($result['id'])){
 $q=$pdo->prepare('SELECT segment_id,rower_note FROM segment_notes WHERE result_id=?');$q->execute([$result['id']]);foreach($q->fetchAll() as $n)$saved_segment_notes[$n['segment_id']]=$n['rower_note'];
 $q=$pdo->prepare('SELECT * FROM interval_results WHERE result_id=? ORDER BY segment_id,interval_number');$q->execute([$result['id']]);foreach($q->fetchAll() as $n)$saved_intervals[$n['segment_id']][$n['interval_number']]=$n;
}
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf_token($_POST['csrf_token']??null))$errors[]='Your form expired. Please try again.';
 $distance=trim($_POST['distance']??'');$time=trim($_POST['result_time']??'');$split=trim($_POST['average_split']??'');$rate=trim($_POST['average_rate']??'');$hr=trim($_POST['average_hr']??'');$rpe=trim($_POST['rpe']??'');$attendance=trim($_POST['attendance_status']??'completed');$notes=trim($_POST['rower_notes']??'');
 if(!in_array($attendance,['completed','missed','unavailable'],true))$errors[]='Choose a valid attendance status.';
 if($distance!==''&&(!ctype_digit($distance)||(int)$distance<1))$errors[]='Enter a valid final distance.';
 $seconds=null;if($time!==''){if(!preg_match('/^(?:(\d+):)?([0-5]?\d):([0-5]\d)$/',$time,$m))$errors[]='Enter result time as hh:mm:ss or mm:ss.';else $seconds=((int)($m[1]??0)*3600)+((int)$m[2]*60)+(int)$m[3];}
 if($rate!==''&&(!ctype_digit($rate)||(int)$rate>100))$errors[]='Enter a valid average stroke rate.';
 if($hr!==''&&(!ctype_digit($hr)||(int)$hr<30||(int)$hr>250))$errors[]='Heart rate must be between 30 and 250.';
 if($rpe!==''&&(!ctype_digit($rpe)||(int)$rpe<1||(int)$rpe>10))$errors[]='RPE must be between 1 and 10.';
 if(strlen($notes)>5000)$errors[]='Notes must be 5,000 characters or fewer.';
 foreach(($_POST['intervals']??[]) as $segmentId=>$pieces)foreach($pieces as $number=>$piece){$pieceRate=trim($piece['rate']??'');if($pieceRate!==''&&(!ctype_digit($pieceRate)||(int)$pieceRate>100))$errors[]='Interval rates must be between 1 and 100.';}
 if(!$errors){
  $pdo->beginTransaction();
  $sql='INSERT INTO results (session_id,rower_id,session_type,distance,total_time_seconds,split_500m,stroke_rate,heart_rate,effort_rating,attendance_status,personal_notes,technical_issues) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE distance=VALUES(distance),total_time_seconds=VALUES(total_time_seconds),split_500m=VALUES(split_500m),stroke_rate=VALUES(stroke_rate),heart_rate=VALUES(heart_rate),effort_rating=VALUES(effort_rating),attendance_status=VALUES(attendance_status),personal_notes=VALUES(personal_notes),technical_issues=VALUES(technical_issues)';
  $pdo->prepare($sql)->execute([$id,(int)$_SESSION['user_id'],$training['session_type'],$distance===''?null:$distance,$seconds,$split===''?null:$split,$rate===''?null:$rate,$hr===''?null:$hr,$rpe===''?null:$rpe,$attendance,$notes===''?null:$notes,trim($_POST['technical_notes']??'')?:null]);
  $q=$pdo->prepare('SELECT id FROM results WHERE session_id=? AND rower_id=?');$q->execute([$id,(int)$_SESSION['user_id']]);$resultId=(int)$q->fetchColumn();
  $allowed=array_flip(array_map('strval',array_column($segments,'id')));
  $pdo->prepare('DELETE FROM segment_notes WHERE result_id=?')->execute([$resultId]);$nq=$pdo->prepare('INSERT INTO segment_notes (result_id,segment_id,rower_note) VALUES (?,?,?)');foreach(($_POST['segment_notes']??[]) as $segmentId=>$note){$note=trim($note);if($note!==''&&isset($allowed[(string)$segmentId]))$nq->execute([$resultId,(int)$segmentId,$note]);}
  $pdo->prepare('DELETE FROM interval_results WHERE result_id=?')->execute([$resultId]);$iq=$pdo->prepare('INSERT INTO interval_results (result_id,segment_id,interval_number,result_time,split_500m,stroke_rate) VALUES (?,?,?,?,?,?)');foreach(($_POST['intervals']??[]) as $segmentId=>$pieces){if(!isset($allowed[(string)$segmentId]))continue;foreach($pieces as $number=>$piece){$pieceTime=trim($piece['time']??'');$pieceSplit=trim($piece['split']??'');$pieceRate=trim($piece['rate']??'');if($pieceTime!==''||$pieceSplit!==''||$pieceRate!=='')$iq->execute([$resultId,(int)$segmentId,(int)$number,$pieceTime?:null,$pieceSplit?:null,$pieceRate?:null]);}}
  $pdo->commit();set_session_message('success','Your session submission was saved.');header('Location: /pages/session-view.php?id='.$id);exit;
 }
}
$page_title='Submit result - OarNote';require '../includes/header.php';
?>
<header class="page-header"><div><p class="eyebrow"><?= htmlspecialchars($training['session_type']) ?> session</p><h1><?= htmlspecialchars($training['title']) ?></h1><p>Record how your session went.</p></div><a class="btn btn-secondary" href="/pages/session-view.php?id=<?= $id ?>">Cancel</a></header>
<div class="form-shell card"><?php if($errors): ?><div class="alert alert-error"><div><?php foreach($errors as $e): ?><div><?= htmlspecialchars($e) ?></div><?php endforeach ?></div></div><?php endif ?><form method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(csrf_token()) ?>">
<div class="form-row"><div class="form-group"><label class="form-label">Attendance</label><select name="attendance_status"><option value="completed" <?= ($result['attendance_status']??'completed')==='completed'?'selected':'' ?>>Completed</option><option value="missed" <?= ($result['attendance_status']??'')==='missed'?'selected':'' ?>>Missed</option><option value="unavailable" <?= ($result['attendance_status']??'')==='unavailable'?'selected':'' ?>>Injured / unavailable</option></select></div><div class="form-group"><label class="form-label">RPE / session difficulty <span class="optional">Optional</span></label><select name="rpe"><option value="">Choose 1–10</option><?php for($i=1;$i<=10;$i++): ?><option value="<?= $i ?>" <?= ($result['effort_rating']??'')==$i?'selected':'' ?>><?= $i ?> — <?= $i<=3?'Easy':($i<=7?'Moderate':'Hard') ?></option><?php endfor ?></select></div></div>
<?php if($training['session_type']==='Erg'): ?>
 <?php foreach($segments as $s): if(!in_array($s['segment_type'],['distance_interval','time_interval'],true)||(int)$s['repetitions']<1)continue; ?><section class="interval-entry"><h2><?= (int)$s['repetitions'] ?> × <?= htmlspecialchars($s['work_value']) ?> <?= htmlspecialchars($s['work_unit']) ?></h2><div class="table-scroll"><table class="table interval-table"><thead><tr><th>#</th><th>Time</th><th>Split</th><th>Rate</th></tr></thead><tbody><?php for($i=1;$i<=(int)$s['repetitions'];$i++): $piece=$saved_intervals[$s['id']][$i]??[]; ?><tr><td><?= $i ?></td><td><input name="intervals[<?= (int)$s['id'] ?>][<?= $i ?>][time]" value="<?= htmlspecialchars($piece['result_time']??'') ?>" placeholder="4:10"></td><td><input name="intervals[<?= (int)$s['id'] ?>][<?= $i ?>][split]" value="<?= htmlspecialchars($piece['split_500m']??'') ?>" placeholder="2:05"></td><td><input name="intervals[<?= (int)$s['id'] ?>][<?= $i ?>][rate]" type="number" min="1" max="100" value="<?= htmlspecialchars($piece['stroke_rate']??'') ?>" placeholder="26"></td></tr><?php endfor ?></tbody></table></div></section><?php endforeach ?>
 <div class="form-row"><?php if($training['workout_format']==='single_distance'): ?><div class="form-group"><label class="form-label">Final time</label><input name="result_time" value="<?= isset($result['total_time_seconds'])&&$result['total_time_seconds']!==null?gmdate($result['total_time_seconds']>=3600?'H:i:s':'i:s',$result['total_time_seconds']):'' ?>" placeholder="6:42"></div><?php elseif($training['workout_format']==='single_time'): ?><div class="form-group"><label class="form-label">Final distance (metres)</label><input name="distance" type="number" min="1" value="<?= htmlspecialchars($result['distance']??'') ?>"></div><?php endif ?><div class="form-group"><label class="form-label">Overall average split <span class="optional">Optional</span></label><input name="average_split" maxlength="50" value="<?= htmlspecialchars($result['split_500m']??'') ?>" placeholder="2:05"></div></div>
 <div class="form-row"><div class="form-group"><label class="form-label">Overall average rate <span class="optional">Optional</span></label><input name="average_rate" type="number" min="1" max="100" value="<?= htmlspecialchars($result['stroke_rate']??'') ?>"></div><div class="form-group"><label class="form-label">Average heart rate <span class="optional">Optional</span></label><input name="average_hr" type="number" min="30" max="250" value="<?= htmlspecialchars($result['heart_rate']??'') ?>"></div></div>
<?php else: ?>
 <div class="form-group"><label class="form-label">Average heart rate <span class="optional">Optional</span></label><input name="average_hr" type="number" min="30" max="250" value="<?= htmlspecialchars($result['heart_rate']??'') ?>"></div><div class="form-group"><label class="form-label">Personal technical notes <span class="optional">Optional</span></label><textarea name="technical_notes" maxlength="5000"><?= htmlspecialchars($result['technical_issues']??'') ?></textarea></div><?php foreach($segments as $s): ?><div class="form-group"><label class="form-label">Piece <?= (int)$s['segment_order'] ?> note <span class="optional">Optional</span></label><textarea name="segment_notes[<?= (int)$s['id'] ?>]" maxlength="2000" placeholder="<?= htmlspecialchars($s['title']??'') ?>"><?= htmlspecialchars($saved_segment_notes[$s['id']]??'') ?></textarea></div><?php endforeach ?>
<?php endif ?>
<div class="form-group"><label class="form-label">Overall session notes <span class="optional">Optional</span></label><textarea name="rower_notes" maxlength="5000"><?= htmlspecialchars($result['personal_notes']??'') ?></textarea></div><div class="form-actions"><a class="btn btn-secondary" href="/pages/session-view.php?id=<?= $id ?>">Cancel</a><button class="btn btn-primary" type="submit">Save submission</button></div></form></div>
<?php require '../includes/footer.php'; ?>
