<?php
session_start();require_once '../includes/auth.php';require_once '../includes/messages.php';require_login();require '../config/database.php';require_once '../includes/workout-display.php';
function display_interval_results(PDO $pdo,int $resultId){$q=$pdo->prepare('SELECT ir.*,ws.segment_order,ws.work_value,ws.work_unit FROM interval_results ir JOIN workout_segments ws ON ws.id=ir.segment_id WHERE ir.result_id=? ORDER BY ws.segment_order,ir.interval_number');$q->execute([$resultId]);$rows=$q->fetchAll();if(!$rows)return;?><div class="table-scroll"><table class="table interval-table compact"><thead><tr><th>#</th><th>Time</th><th>Split</th><th>Rate</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?= (int)$row['interval_number'] ?></td><td><?= htmlspecialchars($row['result_time']?:'—') ?></td><td><?= htmlspecialchars($row['split_500m']?:'—') ?></td><td><?= htmlspecialchars($row['stroke_rate']?:'—') ?></td></tr><?php endforeach ?></tbody></table></div><?php }
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);if(!$id){http_response_code(404);exit('Session not found.');}
$q=$pdo->prepare("SELECT s.*,CONCAT(u.first_name,' ',u.last_name) coach_name FROM sessions s JOIN users u ON u.id=s.coach_id WHERE s.id=?");$q->execute([$id]);$session=$q->fetch();if(!$session){http_response_code(404);exit('Session not found.');}
$q=$pdo->prepare('SELECT * FROM workout_segments WHERE session_id=? ORDER BY segment_order,id');$q->execute([$id]);$segments=$q->fetchAll();$is_coach=get_user_role()==='coach';
if($is_coach&&$session['coach_id']!=(int)$_SESSION['user_id']){http_response_code(403);exit('You do not have permission to view this session.');}
$result=null;$submissions=[];if($is_coach){$q=$pdo->prepare("SELECT r.*,CONCAT(u.first_name,' ',u.last_name) rower_name,f.feedback_text FROM results r JOIN users u ON u.id=r.rower_id LEFT JOIN feedback f ON f.result_id=r.id WHERE r.session_id=? ORDER BY u.first_name,u.last_name");$q->execute([$id]);$submissions=$q->fetchAll();}else{$q=$pdo->prepare('SELECT r.*,f.feedback_text FROM results r LEFT JOIN feedback f ON f.result_id=r.id WHERE r.session_id=? AND r.rower_id=?');$q->execute([$id,(int)$_SESSION['user_id']]);$result=$q->fetch();}
$page_title=$session['title'].' - OarNote';require '../includes/header.php';?>
<header class="page-header"><div><p class="eyebrow"><?= htmlspecialchars($session['session_type']) ?> session · <?= date('M j, Y',strtotime($session['date'])) ?></p><h1><?= htmlspecialchars($session['title']) ?></h1><div class="session-badges"><span class="status-pill status-<?= htmlspecialchars($session['status']) ?>"><?= htmlspecialchars($session['status']==='open'?'Open for Results':ucfirst($session['status'])) ?></span><?php if($session['purpose']): ?><span class="type-pill"><?= htmlspecialchars($session['purpose']) ?></span><?php endif ?><?php if($session['boat_class']): ?><span class="type-pill">Boat <?= htmlspecialchars($session['boat_class']) ?></span><?php endif ?></div><p>Programmed by <?= htmlspecialchars($session['coach_name']) ?></p></div><a href="/pages/dashboard.php" class="btn btn-secondary">Back to sessions</a></header>
<?php if($session['coach_notes']): ?><section class="general-note card"><p class="eyebrow">Session notes</p><p><?= nl2br(htmlspecialchars($session['coach_notes'])) ?></p></section><?php endif ?>
<section class="workout-display"><?php foreach($segments as $i=>$segment)display_workout_segment($segment,$i+1); ?></section>
<?php if(!$is_coach): ?><section class="submission-panel card"><div class="card-body"><h2><?= $result?'Your submission':'Submit your session' ?></h2><?php if($result): ?><div class="result-summary"><p><strong>Attendance:</strong> <?= htmlspecialchars(ucfirst(str_replace('unavailable','injured / unavailable',$result['attendance_status']))) ?> · <strong>RPE:</strong> <?= htmlspecialchars($result['effort_rating']?:'—') ?>/10</p><?php if($session['session_type']==='Erg'): ?><p><strong>Result:</strong> <?= $result['distance']?number_format($result['distance']).' m':($result['total_time_seconds']?floor($result['total_time_seconds']/60).':'.str_pad($result['total_time_seconds']%60,2,'0',STR_PAD_LEFT):'—') ?></p><p><strong>Average split:</strong> <?= htmlspecialchars($result['split_500m']?:'—') ?> · <strong>Rate:</strong> <?= htmlspecialchars($result['stroke_rate']?:'—') ?> · <strong>HR:</strong> <?= htmlspecialchars($result['heart_rate']?:'—') ?></p><?php display_interval_results($pdo,(int)$result['id']);endif ?><p><?= nl2br(htmlspecialchars($result['personal_notes']?:'No notes added.')) ?></p><?php if($result['feedback_text']): ?><div class="coach-note"><strong>Coach feedback</strong><p><?= nl2br(htmlspecialchars($result['feedback_text'])) ?></p></div><?php endif ?></div><a class="btn btn-secondary" href="/pages/performance-submit.php?id=<?= $id ?>">Edit submission</a><?php elseif($session['status']==='open'): ?><p class="text-muted">Record your result and notes after completing this workout.</p><a class="btn btn-primary" href="/pages/performance-submit.php?id=<?= $id ?>">Add result</a><?php else: ?><p class="text-muted">Results are not currently open for this session.</p><?php endif ?></div></section>
<?php else: ?><section class="review-section"><div class="section-heading"><div><p class="eyebrow">Coach review</p><h2>Rower submissions</h2></div><p><?= count($submissions) ?> submitted</p></div><?php if(!$submissions): ?><div class="card empty-state"><p class="text-muted">No rowers have submitted this session yet.</p></div><?php endif;foreach($submissions as $r): ?><article class="card review-card"><div class="card-body"><div class="flex-between"><h3><?= htmlspecialchars($r['rower_name']) ?></h3><a class="btn btn-secondary btn-small" href="/pages/feedback.php?result_id=<?= (int)$r['id'] ?>">Add feedback</a></div><div class="review-stats"><span><small>Attendance</small><?= htmlspecialchars(ucfirst(str_replace('unavailable','injured / unavailable',$r['attendance_status']))) ?></span><span><small>RPE</small><?= htmlspecialchars($r['effort_rating']?:'—') ?>/10</span><?php if($session['session_type']==='Erg'): ?><span><small>Result</small><?= $r['distance']?number_format($r['distance']).' m':($r['total_time_seconds']?floor($r['total_time_seconds']/60).':'.str_pad($r['total_time_seconds']%60,2,'0',STR_PAD_LEFT):'—') ?></span><span><small>Avg split</small><?= htmlspecialchars($r['split_500m']?:'—') ?></span><span><small>Rate</small><?= htmlspecialchars($r['stroke_rate']?:'—') ?></span><?php endif ?><span><small>Heart rate</small><?= htmlspecialchars($r['heart_rate']?:'—') ?></span></div><?php if($session['session_type']==='Erg')display_interval_results($pdo,(int)$r['id']); ?><p><?= nl2br(htmlspecialchars($r['personal_notes']?:'No overall notes.')) ?></p><?php $n=$pdo->prepare('SELECT sn.rower_note,ws.segment_order,ws.title FROM segment_notes sn JOIN workout_segments ws ON ws.id=sn.segment_id WHERE sn.result_id=? ORDER BY ws.segment_order');$n->execute([$r['id']]);foreach($n->fetchAll() as $note): ?><p class="segment-rower-note"><strong>Piece <?= (int)$note['segment_order'] ?>:</strong> <?= nl2br(htmlspecialchars($note['rower_note'])) ?></p><?php endforeach;if($r['feedback_text']): ?><div class="coach-note"><strong>Your feedback</strong><p><?= nl2br(htmlspecialchars($r['feedback_text'])) ?></p></div><?php endif ?></div></article><?php endforeach ?></section><?php endif ?>
<?php require '../includes/footer.php';?>
